version: "3.9"
services:
  consul:
    image: consul
    ports:
      - "8500:8500"
    restart: always

  demo-web-api:
    image: web-api
    build:
        context: .
        dockerfile: Demo.Api/Dockerfile
    ports:
      - "5004:80"
    depends_on:
      - consul
    restart: always
  
  demo-identity-server:
    image: id
    build:
        context: .
        dockerfile: Demo.IdentityService/Dockerfile
    ports:
      - "5005:80"
    restart: always

#  email-service:
#    image: email
#    build:
#      context: .
#      dockerfile: Demo.EmailService/Dockerfile
#    ports:
#      - "7145:80"
#    restart: always

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    depends_on:
      - consul
    restart: always